name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 4'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: "Update all nugets to latest version"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET (LTS)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            6.0.x

      - name: Show .NET info
        run: dotnet --info

      - name: Restore (test)
        run: dotnet restore --no-cache

      - name: Update packages
        id: update
        uses: tjololo/nuget-dependencies-update@v1
        with:
          version-limit: 'minor'
          comment-updated: true
          ignore: |
            StackExchange.Redis.Extensions.Newtonsoft

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Updated nuget dependencies"
          body: ${{ steps.update.outputs.body }}
          commit-message: "chore: bump NuGet dependencies"
          branch: "chore/update-nugets"
          base: main
          labels: dependencies
